# Site settings (UltiBridge Unity)
[site]
  title = "UltiBridge | Unity"
  banner = "images/BannerUltiBridge.webp"
  research_link_text = "Unity Documentation"
  research_link_url = "https://docs.unity3d.com/"
  research_link_enabled = false

# Theme colors (Monochrome theme)
[theme_colors]
  brand_primary = "#FFFFFF"
  bg_dark = "#0F0F0F"
  text_white = "#FFFFFF"

# Open Graph / SEO (optional)
[meta]
  og_type = "website"
  og_url = "https://ultikynnys.com/ultibridge/unity"
  og_title = "UltiBridge | Unity"
  og_description = "Seamless bridge between Blender and Unity for efficient asset workflows."
  og_image = "images/UltiBridge2_Unity.webp"

# Section titles (optional overrides)
[titles]
  comparisons = "Unity Workflow Comparisons"
  showcase = "Unity Integration Showcase"
  support = "Unity Community"

# Introduction section
[introduction]
  title = ""
  paragraphs = [
    "Streamline your **Blender to Unity** workflow with UltiBridge's powerful asset pipeline.",
    "Export models, animations, and materials with **one-click precision** directly to Unity projects.",
    "Maintain **perfect fidelity** across your creative pipeline with automated optimization."
  ]

  # Parameters and Usage sections
  parameters_title = "Unity Features"
  parameters = [
    "**Direct Export** - Send assets directly to Unity project folders.",
    "**Material Mapping** - Automatic Unity material creation and assignment.",
    "**LOD Generation** - Create multiple detail levels for Unity's LOD system.",
    "**Prefab Creation** - Generate Unity prefabs with proper component setup.",
    "**Animation Export** - Transfer Blender animations to Unity's Animator system.",
    "**Lightmap UVs** - Generate secondary UV channels for Unity lightmapping."
  ]

  usage_title = "Unity Workflow"
  usage_steps = [
    "**Configure** Unity project path in UltiBridge settings.",
    "**Select** your Blender assets (meshes, materials, animations).",
    "**Choose** export options: LODs, materials, prefabs, etc.",
    "**Click Export to Unity** - assets appear instantly in your Unity project.",
    "**Iterate** seamlessly between Blender and Unity with live sync."
  ]

  usage_image = "images/UltiBridge2_Unity.webp"
  usage_image_alt = "UltiBridge Unity integration interface"
  usage_image_caption = "UltiBridge panel showing Unity-specific export options"

# Comparisons (Before/After sliders)
[[comparisons]]
  initial = 0.3
  before = "images/Logo.webp"
  after  = "images/UltiBridge2_Unity.webp"
  caption = "**Traditional workflow** vs **UltiBridge Unity integration**"
  handle_shape = "circle"

[[comparisons]]
  initial = 0.6
  before = "images/Logo.webp"
  after  = "images/UltiBridge2_Unity.webp"
  caption = "**Manual export process** vs **automated Unity pipeline**"
  handle_shape = "circle"

[[comparisons]]
  initial = 0.4
  before = "images/Logo.webp"
  after  = "images/UltiBridge2_Unity.webp"
  caption = "**Material recreation** vs **automatic Unity material mapping**"
  handle_shape = "circle"

# Showcase video
[showcase]
  placeholder = "Unity integration demo video coming soon"

# Support / Community
[support]
  title = "Unity Community"
  text = "Connect with **Unity developers** using UltiBridge in their production pipelines."
  link_text = "Join Unity Community"
  link_url = "https://discord.gg/J7kWSfM4jw"

# Citations configuration - disabled for UltiBridge Unity
[citations_config]
  enabled = false

# Citations (optional - disabled, this citation is for CoACD research)
# [[citations]]
#   id = "wei2022approximate"
#   bibtex = "@article{wei2022approximate,\n  title={Approximate convex decomposition for 3d meshes with collision-aware concavity and tree search},\n  author={Wei, Xinyue and Liu, Minghua and Ling, Zhan and Su, Hao},\n  journal={ACM Transactions on Graphics (TOG)},\n  volume={41},\n  number={4},\n  pages={1--18},\n  year={2022},\n  publisher={ACM New York, NY, USA}\n}"
