# Site settings (Version 3)
[site]
  title = "UltiBridge | Unreal Engine"
  banner = "images/BannerUltiBridge.webp"
  research_link_text = "Unreal Engine Documentation"
  research_link_url = "https://docs.unrealengine.com/"
  research_link_enabled = false

# Theme colors (Monochrome theme)
[theme_colors]
  brand_primary = "#FFFFFF"
  bg_dark = "#0F0F0F"
  text_white = "#FFFFFF"

# Font configuration (references shared font config)
fonts_config = "content/fonts.toml"

# Open Graph / SEO (optional)
[meta]
  og_type = "website"
  og_url = "https://ultikynnys.com/ultibridge/unreal"
  og_title = "UltiBridge | Unreal Engine"
  og_description = "Seamless bridge between Blender and Unreal Engine for production-ready asset workflows."
  og_image = "images/UltiBridge2_Unreal.webp"

# Section titles (optional overrides)
[titles]
  comparisons = "Unreal Workflow Comparisons"
  showcase = "Unreal Integration Showcase"
  support = "Unreal Community"

# Introduction section
[introduction]
  title = ""
  paragraphs = [
    "Accelerate your **Blender to Unreal Engine** pipeline with UltiBridge.",
    "Export meshes, materials, and animations with **one-click** directly into Unreal's Content Browser.",
    "Maintain **fidelity** and project structure with automation tailored for Unreal."
  ]

  # Parameters and Usage sections
  parameters_title = "Unreal Features"
  parameters = [
    "**Direct Export** - Send assets straight to Unreal's Content Browser.",
    "**Material Instances** - Map Blender materials to Unreal material instances.",
    "**LOD Groups** - Generate and assign LODs compatible with Unreal import.",
    "**Collision Meshes** - Export UCX/UBX-style colliders for Unreal physics.",
    "**Animation Export** - Transfer rigs and actions compatible with Unreal's animation system.",
    "**Project Structure** - Organize assets into Unreal-friendly folder layouts."
  ]

  usage_title = "Unreal Workflow"
  usage_steps = [
    "**Configure** your Unreal project path in UltiBridge settings.",
    "**Select** Blender assets (meshes, materials, animations).",
    "**Choose** export options: LODs, materials, collisions, etc.",
    "**Export to Unreal** - assets appear in the Content Browser.",
    "**Iterate** quickly with a streamlined Blender ⇄ Unreal loop."
  ]

  usage_image = "images/UltiBridge2_Unreal.webp"
  usage_image_alt = "UltiBridge Unreal integration interface"
  usage_image_caption = "UltiBridge panel showing Unreal-specific export options"
  usage_image_2 = "images/Logo.webp"
  usage_image_2_alt = "Batch processing interface"
  usage_image_2_caption = "Batch processing tools for production workflows"

# Comparisons (Before/After sliders)
[[comparisons]]
  initial = 0.3
  before = "images/Logo.webp"
  after  = "images/UltiBridge2_Unreal.webp"
  caption = "**Traditional workflow** vs **UltiBridge Unreal integration**"
  handle_shape = "circle"

[[comparisons]]
  initial = 0.6
  before = "images/Logo.webp"
  after  = "images/UltiBridge2_Unreal.webp"
  caption = "**Manual export process** vs **automated Unreal pipeline**"
  handle_shape = "circle"

[[comparisons]]
  initial = 0.4
  before = "images/Logo.webp"
  after  = "images/UltiBridge2_Unreal.webp"
  caption = "**Material recreation** vs **automatic Unreal material mapping**"
  handle_shape = "circle"

[[comparisons]]
  initial = 0.6
  before = "images/Logo.webp"
  after  = "images/UltiBridge2_Unreal.webp"
  caption = "**Multiple steps** vs **streamlined Content Browser import**"
  handle_shape = "circle"

# Showcase video
[showcase]
  # video_url = "https://www.youtube.com/embed/UNREAL_DEMO_VIDEO_ID"
  placeholder = "Unreal integration demo video coming soon"

# Support / Community
[support]
  title = "Unreal Community"
  text = "Addon support and feedback."
  link_text = "Support Discord"
  link_url = "https://discord.gg/J7kWSfM4jw"

# Citations configuration - disabled for UltiBridge Unreal
[citations_config]
  enabled = false

# Citations (optional - disabled, these citations are for CoACD research)
# [[citations]]
#   id = "wei2022approximate"
#   bibtex = "@article{wei2022approximate,\n  title={Approximate convex decomposition for 3d meshes with collision-aware concavity and tree search},\n  author={Wei, Xinyue and Liu, Minghua and Ling, Zhan and Su, Hao},\n  journal={ACM Transactions on Graphics (TOG)},\n  volume={41},\n  number={4},\n  pages={1--18},\n  year={2022},\n  publisher={ACM New York, NY, USA}\n}"

# [[citations]]
#   id = "advanced2023"
#   bibtex = "@inproceedings{advanced2023,\n  title={Advanced Collision Detection in Real-time Applications},\n  author={Smith, John and Doe, Jane},\n  booktitle={Proceedings of Computer Graphics International},\n  pages={123--135},\n  year={2023},\n  publisher={IEEE}\n}"
